#!/usr/bin/env python
from dropbox import client, rest, session
import webbrowser
# Get your app key and secret from the Dropbox developer website

class NameGetter(object):

    def function(self):
        APP_KEY = 'kgly5xtoh1t8dwj'
        APP_SECRET = '5pn9tbg5uwtnn58'

        # ACCESS_TYPE should be 'dropbox' or 'app_folder' as configured for your app
        ACCESS_TYPE = 'dropbox'

        sess = session.DropboxSession(APP_KEY, APP_SECRET, ACCESS_TYPE)

        request_token = sess.obtain_request_token()

        url = sess.build_authorize_url(request_token)

        # Make the user sign in and authorize this token
        #print "url:", url
        webbrowser.open(url, new=1, autoraise=True)
        print "Please visit this website and press the 'Allow' button, then hit 'Enter' here."
        raw_input()
        # This will fail if the user didn't visit the above URL and hit 'Allow'
        access_token = sess.obtain_access_token(request_token)

        client = client.DropboxClient(sess)
        print "linked account:", client.account_info()
        f = open('document.txt')
        response = client.put_file('/magnum-opus.txt', f)
    def run(self):
        self.function()
        
if __name__ == '__main__':
    ng = NameGetter()
    ng.run()
